#!/bin/bash
set -e
echo "CREATE USER $APP_USER WITH ENCRYPTED PASSWORD '$APP_PASSWORD';"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_USER WITH ENCRYPTED PASSWORD '$APP_PASSWORD';
	CREATE DATABASE $APP_DB;
	GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
EOSQL